services:
  db:
    container_name: AuthDB
    image: postgres 
    environment:
      POSTGRES_DB: authDB
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data 


  app:
    container_name: AuthAPI
    build:
      context: . 
    ports:
      - "8080:8080"  
    depends_on:
      - db  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/authDB  
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: